# Generated by Django 5.1.5 on 2025-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.TextField(default='group'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.TextField(default='__default__'),
        ),
    ]
