version: '3.8'

services:
  web:
    build: 
      context: ../..  # Path to root directory
      dockerfile: deployment/Dockerfile  # Path to Dockerfile from context
    command: daphne -b 0.0.0.0 -p 8000 chatapp.asgi:application
    volumes:
      - ../..:/app
    environment:
      - DJANGO_SETTINGS_MODULE=chatapp.settings
      - REDIS_HOST=redis #???
      # - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - redis
      # - db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # db:
  #   image: postgres:14-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=dbname
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../static:/app/static
      - ../../media:/app/media
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Updated path
    depends_on:
      - web

volumes:
  postgres_data:
