version: '3.3'
services:
  web:
    build: 
      context: ../..
      dockerfile: deployment/Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 chatapp.asgi:application
    environment:
      - DJANGO_SETTINGS_MODULE=chatapp.settings
      - REDIS_HOST=redis
      - SECRET_KEY=your_secret_key
      - DEBUG=0
      - ALLOWED_HOSTS=ec2-3-111-67-65.ap-south-1.compute.amazonaws.com,3.111.67.65,localhost
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge